version: '3.8'
services:
  server:
    container_name: server
    build:
     context: .
     dockerfile: Dockerfile.server
    command: 'npm run start:dev --host 0.0.0.0'
    volumes:
      - ./server:/app/www/server
      - checkboxai_volume:/server/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - checkboxai-networks

  client:
    container_name: client
    build:
     context: .
     dockerfile: Dockerfile.client
    command: 'npm run dev'
    volumes:
      - ./client:/app/www/client
      - checkboxai_volume:/client/node_modules
    ports:
      - 3000:3000
    networks:
      - checkboxai-networks
    environment:
       - CHOKIDAR_USEPOLLING=true

  checkboxai_mysql:
    image: mysql:5.7
    container_name: checkboxai_db
    networks:
      - checkboxai-networks
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_HOST: "%"
    ports: 
      - ${DB_PORT}:${DB_PORT}
    volumes:
     - checkboxai_volume:/var/lib/mysql

networks:
  checkboxai-networks:
    driver: bridge

volumes:
  checkboxai_volume: